// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXkmcbAl8nY3T4PRaj2Am9AQNSO-jAjP4',
    appId: '1:778851391746:web:476fc08a445b652a014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    authDomain: 'talky-2026.firebaseapp.com',
    storageBucket: 'talky-2026.firebasestorage.app',
    measurementId: 'G-TGJXMRMJYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZZ3-nee1i2BfMzxUSpyey7ZZO9yDTclM',
    appId: '1:778851391746:android:066ce9f55ed7eb73014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    storageBucket: 'talky-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFSkqoytmJxDGiC-KUhpgkbOFdbRjc4A',
    appId: '1:778851391746:ios:eab9030a38d3355f014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    storageBucket: 'talky-2026.firebasestorage.app',
    androidClientId:
        '778851391746-bbu44ab95l6nnskjcih3b2th14ie9mbp.apps.googleusercontent.com',
    iosClientId:
        '778851391746-vnt844dgmhl1ud7lenvsfb7rvbrhd1ek.apps.googleusercontent.com',
    iosBundleId: 'com.example.talky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlFSkqoytmJxDGiC-KUhpgkbOFdbRjc4A',
    appId: '1:778851391746:ios:eab9030a38d3355f014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    storageBucket: 'talky-2026.firebasestorage.app',
    androidClientId:
        '778851391746-bbu44ab95l6nnskjcih3b2th14ie9mbp.apps.googleusercontent.com',
    iosClientId:
        '778851391746-vnt844dgmhl1ud7lenvsfb7rvbrhd1ek.apps.googleusercontent.com',
    iosBundleId: 'com.example.talky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXkmcbAl8nY3T4PRaj2Am9AQNSO-jAjP4',
    appId: '1:778851391746:web:2063bbd1924a0acb014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    authDomain: 'talky-2026.firebaseapp.com',
    storageBucket: 'talky-2026.firebasestorage.app',
    measurementId: 'G-DZ0Y3LJJXJ',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCXkmcbAl8nY3T4PRaj2Am9AQNSO-jAjP4',
    appId: '1:778851391746:web:476fc08a445b652a014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    authDomain: 'talky-2026.firebaseapp.com',
    storageBucket: 'talky-2026.firebasestorage.app',
  );
}
